### ISSUE TITLE
Fixing AR-docs GitHub Page hosting

### ISSUE THREAD

**Issue by ZoltanVeres** [jeromeetienne/AR.js-docs#2]
@jeromeetienne I mentioned to you this on gitter, that this repository is not accessible as a GitHub page.
I forked this repository to figure out why this is not working, thankfully i managed to fix it in my forked repo, you can check it out here [https://zoltanveres.github.io/AR.js-docs/docs/index.html
](https://zoltanveres.github.io/AR.js-docs/docs/index.html).

I wanted to creat a pull request upon your suggestion, but this cannot be fixed with that.
So here are steps which helped fix this:
1. Enable github pages for the site on Settings -> Github Pages section and choose master branch (see attached image):
![gh](https://user-images.githubusercontent.com/214139/32266730-29714388-bef1-11e7-8479-129f498c4b03.png)

2. Replace the description url from [https://jeromeetienne.github.io/ar.js-docs/](https://jeromeetienne.github.io/ar.js-docs/) to [https://jeromeetienne.github.io/AR.js-docs/docs/index.html](https://jeromeetienne.github.io/AR.js-docs/docs/index.html)

I know this is sort of a half-measure solution, but it gets the job done. Let me know what you think.

**Comment by jeromeetienne** [comment]
Thanks!
